/**
 * src/db/schema.ts — Database schema (SQL DDL)
 *
 * Defines all three tables Flightplan uses in Phase 1.
 * Applied once at DB open time via applySchema() in connection.ts.
 *
 * Tables:
 *   config           — key/value store for user settings (from init)
 *   active_session   — single-row table tracking the current session
 *   usage_snapshots  — historical archive of completed sessions
 *
 * Design principles:
 *   - All CREATE statements use IF NOT EXISTS — safe to re-run on every open.
 *   - No ALTER TABLE in Phase 1 — schema changes get new columns in Phase 2.
 *   - Timestamps stored as ISO 8601 text (SQLite has no native datetime type).
 *   - INTEGER for token counts — SQLite integers go up to 2^63, plenty of room.
 *
 * Phase 2 additions (not yet):
 *   - usage_snapshots.confidence REAL (Dead Reckoning confidence score)
 *   - pattern_library table (velocity profiles)
 *
 * Phase 3 additions (not yet):
 *   - flock_profiles table (community Formation Trust data)
 */

// ─── Table: flightplan_meta ────────────────────────────────────────────────────

/**
 * Key/value metadata table for Flightplan internals.
 *
 * MIGRATION POLICY (read this before editing):
 *   - Schema changes bump `schema_version` and ship as numbered migration steps.
 *   - Never edit shipped DDL — add new statements below existing ones.
 *   - Migrations branch on a single SELECT of schema_version.
 *   - Version is a string so we can use semver-style values in future if needed.
 *
 * Keys written at schema apply time:
 *   schema_version — current schema version number (e.g. '1')
 */
const FLIGHTPLAN_META_TABLE = `
  CREATE TABLE IF NOT EXISTS flightplan_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );
`;

/**
 * Seed schema_version = '1' on first open.
 * INSERT OR IGNORE means this only runs once — re-runs are safe no-ops.
 */
const FLIGHTPLAN_META_SEED = `
  INSERT OR IGNORE INTO flightplan_meta (key, value) VALUES ('schema_version', '1');
`;



/**
 * Key/value store for everything set at init.
 *
 * Keys written by cli.ts:
 *   provider_name      — "Claude Code", "Codex", etc.
 *   provider_key       — slug: "claude_code", "codex", etc.
 *   session_baseline   — token budget as string (e.g. "40000")
 *   baseline_source    — "default" | "manual" | "calibrated" | "api"
 *   warn_threshold     — warning percentage as string (e.g. "25", "0" = disabled)
 *   initialized_at     — ISO timestamp of first init
 *
 * updated_at lets us see when a setting was last changed (useful for debugging).
 */
const CONFIG_TABLE = `
  CREATE TABLE IF NOT EXISTS config (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
`;

// ─── Table: active_session ─────────────────────────────────────────────────────

/**
 * Single-row table representing the currently open session.
 * id is always 'current' — there is only ever one row.
 *
 * Lifecycle:
 *   - session_start writes/updates this row with a new session_id.
 *   - get_runway reads it to determine PREFLIGHT vs active level.
 *   - record_session reads it, archives to usage_snapshots, then clears it.
 *
 * Nullable fields:
 *   session_id is NULL when no session is active (PREFLIGHT state).
 *   All other fields are nullable for the same reason — the row may exist
 *   but be empty between sessions.
 *
 * project_id:
 *   Optional — lets agents tag sessions to a specific project.
 *   Nullable in Phase 1. Phase 2 uses it for project-specific velocity.
 */
const ACTIVE_SESSION_TABLE = `
  CREATE TABLE IF NOT EXISTS active_session (
    id               TEXT PRIMARY KEY DEFAULT 'current',
    session_id       TEXT,
    started_at       TEXT,
    goose_level      TEXT,
    tokens_observed  INTEGER NOT NULL DEFAULT 0,
    provider         TEXT,
    model            TEXT,
    project_id       TEXT
  );
`;

/**
 * Seed the active_session row so get_runway() always finds a row to read.
 * Uses INSERT OR IGNORE — only inserts if the row doesn't exist yet.
 * All nullable fields start as NULL (= PREFLIGHT state).
 */
const ACTIVE_SESSION_SEED = `
  INSERT OR IGNORE INTO active_session (id) VALUES ('current');
`;

// ─── Table: usage_snapshots ────────────────────────────────────────────────────

/**
 * Historical archive of completed sessions.
 * Populated by record_session at the end of each session.
 *
 * Phase 2 Dead Reckoning reads this table to calculate:
 *   - Average tokens per session (refines session_baseline)
 *   - Burn rate velocity over time
 *   - Project-specific patterns (via project_id)
 *
 * session_id:
 *   UUID generated by session_start. Stable identifier for a session
 *   even after it's archived. Useful for deduplication if record_session
 *   is called more than once (the UNIQUE constraint prevents double-archiving).
 *
 * tokens_total:
 *   The final token count reported by the agent at session end.
 *   This is the ground truth for Dead Reckoning calibration.
 *
 * duration_minutes:
 *   Calculated at record time from started_at to ended_at.
 *   Stored as REAL so we can have fractional minutes (e.g. 47.3 min).
 *
 * goose_level_final:
 *   The level at session end. Useful for understanding how often users
 *   hit HONK vs LANDING cleanly.
 */
const USAGE_SNAPSHOTS_TABLE = `
  CREATE TABLE IF NOT EXISTS usage_snapshots (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id                  TEXT    NOT NULL UNIQUE,
    started_at                  TEXT    NOT NULL,
    ended_at                    TEXT    NOT NULL,
    duration_minutes            REAL,
    tokens_total                INTEGER NOT NULL,
    goose_level_final           TEXT,
    provider                    TEXT,
    model                       TEXT,
    project_id                  TEXT,
    baseline_at_time            INTEGER,
    notes                       TEXT,

    -- Phase 2 calibration fields (populated by Phase 2; null in Phase 1) --

    -- Was the baseline 'default', 'manual', 'calibrated', or 'api'
    -- when this session ran? Phase 2 needs to know which sessions to mix.
    baseline_source_at_time     TEXT,

    -- Boolean flag (SQLite has no native bool): 1 = exclude from calibration.
    -- User or auto-detection can mark outlier sessions without deleting them.
    excluded_from_calibration   INTEGER NOT NULL DEFAULT 0,

    -- JSON array of session tags, e.g. '["debugging","refactor"]'.
    -- Phase 2 pattern classification uses these for velocity grouping.
    -- null in Phase 1.
    tags                        TEXT
  );
`;

// ─── Schema export ─────────────────────────────────────────────────────────────

/**
 * Ordered list of SQL statements to execute when the DB first opens.
 * connection.ts runs these in sequence inside a transaction.
 *
 * Order matters:
 *   1. Tables must exist before we try to seed them.
 *   2. All IF NOT EXISTS / OR IGNORE — safe to re-run on every app start.
 *
 * MIGRATION POLICY: Never edit existing statements. Add new ones below,
 * and bump schema_version in flightplan_meta when Phase 2 ships.
 */
export const SCHEMA_STATEMENTS = [
  FLIGHTPLAN_META_TABLE,
  FLIGHTPLAN_META_SEED,
  CONFIG_TABLE,
  ACTIVE_SESSION_TABLE,
  ACTIVE_SESSION_SEED,
  USAGE_SNAPSHOTS_TABLE,
] as const;
